framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    default_locale: '%locale%'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        cookie_domain: '%env(string:SESSION_COOKIE_DOMAIN)%'
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true
    
    assets:
        base_urls: '%cdn_base_url%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
        form:
            csrf_protection:
                enabled: false
