<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260712044504 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {

        $this->addSql('CREATE TABLE catalogs (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_F3AD370A115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE catalogs_products (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', catalog_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_322616D94584665A (product_id), INDEX IDX_322616D9CC3C66FC (catalog_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE categories (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, image VARCHAR(255) DEFAULT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_3AF34668115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', region_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', names VARCHAR(5000) NOT NULL, description VARCHAR(5000) NOT NULL, name VARCHAR(150) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_D95DB16B98260155 (region_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities_catalogs (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', city_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', catalogs_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_6E347EBA8BAC62AF (city_id), INDEX IDX_6E347EBA53B63F74 (catalogs_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities_categories (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', city_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', categories_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_D1368C7D8BAC62AF (city_id), INDEX IDX_D1368C7DA21214B7 (categories_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities_coupons (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', city_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', coupons_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_BE5A0E9D8BAC62AF (city_id), INDEX IDX_BE5A0E9D6D72B15C (coupons_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities_domains (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', city_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_C745A0188BAC62AF (city_id), INDEX IDX_C745A018115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities_modules (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', city_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', modules_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_65895C528BAC62AF (city_id), INDEX IDX_65895C5260D6DC42 (modules_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities_payment_methods (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', city_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', payment_methods_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_D4B5919F8BAC62AF (city_id), INDEX IDX_D4B5919F1484032 (payment_methods_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities_points_conditions (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', city_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', point_conditions_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_19D77F548BAC62AF (city_id), INDEX IDX_19D77F548FD2F6B7 (point_conditions_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cities_promotions (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', city_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', promotion_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_1DEFA218BAC62AF (city_id), INDEX IDX_1DEFA21139DF194 (promotion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE colors_scheme (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(100) NOT NULL, color VARCHAR(150) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_BB9F98FF115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(5000) NOT NULL, description VARCHAR(5000) NOT NULL, iso_code VARCHAR(25) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries_catalogs (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', catalogs_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_4E4A4C10F92F3E70 (country_id), INDEX IDX_4E4A4C1053B63F74 (catalogs_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries_categories (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', categories_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_4D09A9E0F92F3E70 (country_id), INDEX IDX_4D09A9E0A21214B7 (categories_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries_coupons (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', coupons_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_AFED17E8F92F3E70 (country_id), INDEX IDX_AFED17E86D72B15C (coupons_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries_domains (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_D6F2B96DF92F3E70 (country_id), INDEX IDX_D6F2B96D115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries_modules (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', modules_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_743E4527F92F3E70 (country_id), INDEX IDX_743E452760D6DC42 (modules_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries_payment_methods (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', payment_methods_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_980C4A89F92F3E70 (country_id), INDEX IDX_980C4A891484032 (payment_methods_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries_points_conditions (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', point_conditions_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_144E8D66F92F3E70 (country_id), INDEX IDX_144E8D668FD2F6B7 (point_conditions_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE countries_promotions (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', promotions_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_9DE1DFBCF92F3E70 (country_id), INDEX IDX_9DE1DFBC10007789 (promotions_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE coupons (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', discount_type_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(150) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_F56411187344E182 (discount_type_id), INDEX IDX_F5641118115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE discount_types (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', operation VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_721A51A7115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE domain_module_features (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', module_feature_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_DB374446115F0EE5 (domain_id), INDEX IDX_DB374446F50193E4 (module_feature_id), UNIQUE INDEX uq_domain_module_feature (domain_id, module_feature_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE domain_modules (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', module_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_CC605ACF115F0EE5 (domain_id), INDEX IDX_CC605ACFAFC2B591 (module_id), UNIQUE INDEX uq_domain_module (domain_id, module_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE domain_templates (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', template_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_8958AFC05DA0FB8 (template_id), UNIQUE INDEX UNIQ_DOMAIN_TEMPLATES_DOMAIN (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE domains (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', tenant_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', domain VARCHAR(500) NOT NULL, logo VARCHAR(500) DEFAULT NULL, notification_email VARCHAR(500) NOT NULL, support_email VARCHAR(500) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_8C7BBF9D9033212A (tenant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE favorite_products (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_19ED42ABA76ED395 (user_id), INDEX IDX_19ED42AB4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE help_message_images (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', help_message_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', image_url VARCHAR(500) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_5E1D162AB9AFDB2B (help_message_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE help_messages (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', to_user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', from_user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', parent_message_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', is_read TINYINT(1) NOT NULL, message LONGTEXT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_54399A9629F6EE60 (to_user_id), INDEX IDX_54399A962130303A (from_user_id), INDEX IDX_54399A9614399779 (parent_message_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE images_products (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', description VARCHAR(255) DEFAULT NULL, order_column INT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_109927304584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE logs (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', code INT DEFAULT NULL, message LONGTEXT NOT NULL, line INT DEFAULT NULL, file VARCHAR(255) DEFAULT NULL, trace LONGTEXT DEFAULT NULL, complete LONGTEXT DEFAULT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE metadata (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', page_type VARCHAR(50) DEFAULT NULL, page_url VARCHAR(255) DEFAULT NULL, meta_title VARCHAR(70) DEFAULT NULL, meta_description VARCHAR(160) DEFAULT NULL, meta_keywords LONGTEXT DEFAULT NULL, canonical_url VARCHAR(255) DEFAULT NULL, robots_directive VARCHAR(100) DEFAULT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_4F143414115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE module_conditions (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', module_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', region_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', city_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_61832234AFC2B591 (module_id), INDEX IDX_61832234F92F3E70 (country_id), INDEX IDX_6183223498260155 (region_id), INDEX IDX_618322348BAC62AF (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE module_features (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', module_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(150) NOT NULL, slug VARCHAR(100) NOT NULL, description VARCHAR(5000) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_DB000FED989D9B62 (slug), INDEX IDX_DB000FEDAFC2B591 (module_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE modules (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(150) NOT NULL, slug VARCHAR(100) NOT NULL, description VARCHAR(5000) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_2EB743D7989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE modules_tenants (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', tenant_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', module_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_CCB1D58F9033212A (tenant_id), INDEX IDX_CCB1D58FAFC2B591 (module_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE orders (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', shipping_country_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', shipping_region_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', shipping_city_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', status_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', coupon_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', total_amount BIGINT NOT NULL, shipping_address LONGTEXT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_E52FFDEEA76ED395 (user_id), INDEX IDX_E52FFDEE41D46E2E (shipping_country_id), INDEX IDX_E52FFDEEDED35062 (shipping_region_id), INDEX IDX_E52FFDEE6DE4646B (shipping_city_id), INDEX IDX_E52FFDEE6BF700BD (status_id), INDEX IDX_E52FFDEE66C5951B (coupon_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE orders_products (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', orders_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', quantity BIGINT NOT NULL, unit_price BIGINT NOT NULL, total_price BIGINT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_749C879CCFFE9AD6 (orders_id), INDEX IDX_749C879C4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_methods (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_4FABF983115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_transactions (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', orders_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', payment_method_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', status_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', amount BIGINT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_8C58AD56CFFE9AD6 (orders_id), INDEX IDX_8C58AD565AA1164F (payment_method_id), INDEX IDX_8C58AD566BF700BD (status_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE point_conditions (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', money_per_point BIGINT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_28132A03115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE points_users (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', orders_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', points VARCHAR(50) NOT NULL, is_won TINYINT(1) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_FF03EDE3CFFE9AD6 (orders_id), INDEX IDX_FF03EDE3A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_reviews (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', rating BIGINT NOT NULL, comment LONGTEXT DEFAULT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_B8A9F0BF4584665A (product_id), INDEX IDX_B8A9F0BFA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE products (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(100) NOT NULL, description LONGTEXT NOT NULL, base_price BIGINT NOT NULL, public_price BIGINT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_B3BA5A5A115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE products_categories (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', category_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_E8ACBE764584665A (product_id), INDEX IDX_E8ACBE7612469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE products_cities_prices (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', city_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', price BIGINT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_EF0906044584665A (product_id), INDEX IDX_EF0906048BAC62AF (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE products_countries_prices (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', price BIGINT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_34E9007A4584665A (product_id), INDEX IDX_34E9007AF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE products_promotions (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', promotion_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_3844C82A139DF194 (promotion_id), INDEX IDX_3844C82A4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE products_regions_prices (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', region_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', price BIGINT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_F6DC7CE34584665A (product_id), INDEX IDX_F6DC7CE398260155 (region_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE promotions (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', discount_type_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, start_date DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', end_date DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', discount_rate BIGINT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_EA1B3034115F0EE5 (domain_id), INDEX IDX_EA1B30347344E182 (discount_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE regions (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(5000) NOT NULL, description VARCHAR(5000) NOT NULL, iso_code VARCHAR(25) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_A26779F3F92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE regions_catalogs (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', region_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', catalogs_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_DBCCC50098260155 (region_id), INDEX IDX_DBCCC50053B63F74 (catalogs_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE regions_categories (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', region_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', categories_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_93AF15B398260155 (region_id), INDEX IDX_93AF15B3A21214B7 (categories_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE regions_coupons (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', region_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', coupons_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_962E852098260155 (region_id), INDEX IDX_962E85206D72B15C (coupons_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE regions_domains (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', region_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_EF312BA598260155 (region_id), INDEX IDX_EF312BA5115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE regions_modules (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', region_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', modules_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_4DFDD7EF98260155 (region_id), INDEX IDX_4DFDD7EF60D6DC42 (modules_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE regions_payment_methods (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', region_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', payment_methods_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7255C7F398260155 (region_id), INDEX IDX_7255C7F31484032 (payment_methods_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE regions_points_conditions (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', region_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', point_condition_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_529709DE98260155 (region_id), INDEX IDX_529709DE7EF86AD2 (point_condition_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE regions_promotions (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', region_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', promotion_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_434763EF98260155 (region_id), INDEX IDX_434763EF139DF194 (promotion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE shopping_cart (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', product_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', quantity INT NOT NULL, added_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_72AAD4F6A76ED395 (user_id), INDEX IDX_72AAD4F64584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE slides (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) DEFAULT NULL, description VARCHAR(3000) DEFAULT NULL, image VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, position INT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_B8C02091115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE statistics (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', ip VARCHAR(150) DEFAULT NULL, device VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, browser VARCHAR(255) DEFAULT NULL, operative_system VARCHAR(255) DEFAULT NULL, lang VARCHAR(255) DEFAULT NULL, page VARCHAR(500) DEFAULT NULL, referrer VARCHAR(500) DEFAULT NULL, referrer_domain VARCHAR(255) DEFAULT NULL, utm_source VARCHAR(255) DEFAULT NULL, utm_medium VARCHAR(255) DEFAULT NULL, utm_campaign VARCHAR(255) DEFAULT NULL, session_id VARCHAR(255) DEFAULT NULL, country_iso_code VARCHAR(5) DEFAULT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_E2D38B22115F0EE5 (domain_id), INDEX idx_stats_domain_date (domain_id, created_at), INDEX idx_stats_domain_country (domain_id, country), INDEX idx_stats_domain_browser (domain_id, browser), INDEX idx_stats_domain_device (domain_id, device), INDEX idx_stats_session (session_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE status (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(50) NOT NULL, description VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE template_images (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', template_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', image_path VARCHAR(500) NOT NULL, image_url VARCHAR(500) NOT NULL, alt_text VARCHAR(255) DEFAULT NULL, sort_order INT NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_EBF7B7985DA0FB8 (template_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE templates (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, slug VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, demo_url VARCHAR(500) DEFAULT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_TEMPLATES_SLUG (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tenants (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(100) NOT NULL, description LONGTEXT NOT NULL, nit VARCHAR(150) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, prefix VARCHAR(15) DEFAULT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', country_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', region_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', city_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, date_of_birth DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', phone VARCHAR(50) DEFAULT NULL, address LONGTEXT DEFAULT NULL, profile_picture VARCHAR(255) DEFAULT NULL, neighborhood VARCHAR(150) DEFAULT NULL, prefix VARCHAR(15) DEFAULT NULL, points VARCHAR(50) DEFAULT NULL, validated_email TINYINT(1) NOT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email), INDEX IDX_1483A5E9115F0EE5 (domain_id), INDEX IDX_1483A5E9F92F3E70 (country_id), INDEX IDX_1483A5E998260155 (region_id), INDEX IDX_1483A5E98BAC62AF (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users_domains (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', domain_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', roles JSON DEFAULT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7C7BCB57A76ED395 (user_id), INDEX IDX_7C7BCB57115F0EE5 (domain_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE catalogs ADD CONSTRAINT FK_F3AD370A115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE catalogs_products ADD CONSTRAINT FK_322616D94584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE catalogs_products ADD CONSTRAINT FK_322616D9CC3C66FC FOREIGN KEY (catalog_id) REFERENCES catalogs (id)');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF34668115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE cities ADD CONSTRAINT FK_D95DB16B98260155 FOREIGN KEY (region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE cities_catalogs ADD CONSTRAINT FK_6E347EBA8BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE cities_catalogs ADD CONSTRAINT FK_6E347EBA53B63F74 FOREIGN KEY (catalogs_id) REFERENCES catalogs (id)');
        $this->addSql('ALTER TABLE cities_categories ADD CONSTRAINT FK_D1368C7D8BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE cities_categories ADD CONSTRAINT FK_D1368C7DA21214B7 FOREIGN KEY (categories_id) REFERENCES categories (id)');
        $this->addSql('ALTER TABLE cities_coupons ADD CONSTRAINT FK_BE5A0E9D8BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE cities_coupons ADD CONSTRAINT FK_BE5A0E9D6D72B15C FOREIGN KEY (coupons_id) REFERENCES coupons (id)');
        $this->addSql('ALTER TABLE cities_domains ADD CONSTRAINT FK_C745A0188BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE cities_domains ADD CONSTRAINT FK_C745A018115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE cities_modules ADD CONSTRAINT FK_65895C528BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE cities_modules ADD CONSTRAINT FK_65895C5260D6DC42 FOREIGN KEY (modules_id) REFERENCES modules (id)');
        $this->addSql('ALTER TABLE cities_payment_methods ADD CONSTRAINT FK_D4B5919F8BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE cities_payment_methods ADD CONSTRAINT FK_D4B5919F1484032 FOREIGN KEY (payment_methods_id) REFERENCES payment_methods (id)');
        $this->addSql('ALTER TABLE cities_points_conditions ADD CONSTRAINT FK_19D77F548BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE cities_points_conditions ADD CONSTRAINT FK_19D77F548FD2F6B7 FOREIGN KEY (point_conditions_id) REFERENCES point_conditions (id)');
        $this->addSql('ALTER TABLE cities_promotions ADD CONSTRAINT FK_1DEFA218BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE cities_promotions ADD CONSTRAINT FK_1DEFA21139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id)');
        $this->addSql('ALTER TABLE colors_scheme ADD CONSTRAINT FK_BB9F98FF115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE countries_catalogs ADD CONSTRAINT FK_4E4A4C10F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id)');
        $this->addSql('ALTER TABLE countries_catalogs ADD CONSTRAINT FK_4E4A4C1053B63F74 FOREIGN KEY (catalogs_id) REFERENCES catalogs (id)');
        $this->addSql('ALTER TABLE countries_categories ADD CONSTRAINT FK_4D09A9E0F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id)');
        $this->addSql('ALTER TABLE countries_categories ADD CONSTRAINT FK_4D09A9E0A21214B7 FOREIGN KEY (categories_id) REFERENCES categories (id)');
        $this->addSql('ALTER TABLE countries_coupons ADD CONSTRAINT FK_AFED17E8F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id)');
        $this->addSql('ALTER TABLE countries_coupons ADD CONSTRAINT FK_AFED17E86D72B15C FOREIGN KEY (coupons_id) REFERENCES coupons (id)');
        $this->addSql('ALTER TABLE countries_domains ADD CONSTRAINT FK_D6F2B96DF92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id)');
        $this->addSql('ALTER TABLE countries_domains ADD CONSTRAINT FK_D6F2B96D115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE countries_modules ADD CONSTRAINT FK_743E4527F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id)');
        $this->addSql('ALTER TABLE countries_modules ADD CONSTRAINT FK_743E452760D6DC42 FOREIGN KEY (modules_id) REFERENCES modules (id)');
        $this->addSql('ALTER TABLE countries_payment_methods ADD CONSTRAINT FK_980C4A89F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id)');
        $this->addSql('ALTER TABLE countries_payment_methods ADD CONSTRAINT FK_980C4A891484032 FOREIGN KEY (payment_methods_id) REFERENCES payment_methods (id)');
        $this->addSql('ALTER TABLE countries_points_conditions ADD CONSTRAINT FK_144E8D66F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id)');
        $this->addSql('ALTER TABLE countries_points_conditions ADD CONSTRAINT FK_144E8D668FD2F6B7 FOREIGN KEY (point_conditions_id) REFERENCES point_conditions (id)');
        $this->addSql('ALTER TABLE countries_promotions ADD CONSTRAINT FK_9DE1DFBCF92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id)');
        $this->addSql('ALTER TABLE countries_promotions ADD CONSTRAINT FK_9DE1DFBC10007789 FOREIGN KEY (promotions_id) REFERENCES promotions (id)');
        $this->addSql('ALTER TABLE coupons ADD CONSTRAINT FK_F56411187344E182 FOREIGN KEY (discount_type_id) REFERENCES discount_types (id)');
        $this->addSql('ALTER TABLE coupons ADD CONSTRAINT FK_F5641118115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE discount_types ADD CONSTRAINT FK_721A51A7115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE domain_module_features ADD CONSTRAINT FK_DB374446115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE domain_module_features ADD CONSTRAINT FK_DB374446F50193E4 FOREIGN KEY (module_feature_id) REFERENCES module_features (id)');
        $this->addSql('ALTER TABLE domain_modules ADD CONSTRAINT FK_CC605ACF115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE domain_modules ADD CONSTRAINT FK_CC605ACFAFC2B591 FOREIGN KEY (module_id) REFERENCES modules (id)');
        $this->addSql('ALTER TABLE domain_templates ADD CONSTRAINT FK_8958AFC0115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE domain_templates ADD CONSTRAINT FK_8958AFC05DA0FB8 FOREIGN KEY (template_id) REFERENCES templates (id)');
        $this->addSql('ALTER TABLE domains ADD CONSTRAINT FK_8C7BBF9D9033212A FOREIGN KEY (tenant_id) REFERENCES tenants (id)');
        $this->addSql('ALTER TABLE favorite_products ADD CONSTRAINT FK_19ED42ABA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE favorite_products ADD CONSTRAINT FK_19ED42AB4584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE help_message_images ADD CONSTRAINT FK_5E1D162AB9AFDB2B FOREIGN KEY (help_message_id) REFERENCES help_messages (id)');
        $this->addSql('ALTER TABLE help_messages ADD CONSTRAINT FK_54399A9629F6EE60 FOREIGN KEY (to_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE help_messages ADD CONSTRAINT FK_54399A962130303A FOREIGN KEY (from_user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE help_messages ADD CONSTRAINT FK_54399A9614399779 FOREIGN KEY (parent_message_id) REFERENCES help_messages (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE images_products ADD CONSTRAINT FK_109927304584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE metadata ADD CONSTRAINT FK_4F143414115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE module_conditions ADD CONSTRAINT FK_61832234AFC2B591 FOREIGN KEY (module_id) REFERENCES modules (id)');
        $this->addSql('ALTER TABLE module_conditions ADD CONSTRAINT FK_61832234F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id)');
        $this->addSql('ALTER TABLE module_conditions ADD CONSTRAINT FK_6183223498260155 FOREIGN KEY (region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE module_conditions ADD CONSTRAINT FK_618322348BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE module_features ADD CONSTRAINT FK_DB000FEDAFC2B591 FOREIGN KEY (module_id) REFERENCES modules (id)');
        $this->addSql('ALTER TABLE modules_tenants ADD CONSTRAINT FK_CCB1D58F9033212A FOREIGN KEY (tenant_id) REFERENCES tenants (id)');
        $this->addSql('ALTER TABLE modules_tenants ADD CONSTRAINT FK_CCB1D58FAFC2B591 FOREIGN KEY (module_id) REFERENCES modules (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE41D46E2E FOREIGN KEY (shipping_country_id) REFERENCES countries (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEDED35062 FOREIGN KEY (shipping_region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE6DE4646B FOREIGN KEY (shipping_city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE6BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE66C5951B FOREIGN KEY (coupon_id) REFERENCES coupons (id)');
        $this->addSql('ALTER TABLE orders_products ADD CONSTRAINT FK_749C879CCFFE9AD6 FOREIGN KEY (orders_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE orders_products ADD CONSTRAINT FK_749C879C4584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE payment_methods ADD CONSTRAINT FK_4FABF983115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE payment_transactions ADD CONSTRAINT FK_8C58AD56CFFE9AD6 FOREIGN KEY (orders_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE payment_transactions ADD CONSTRAINT FK_8C58AD565AA1164F FOREIGN KEY (payment_method_id) REFERENCES payment_methods (id)');
        $this->addSql('ALTER TABLE payment_transactions ADD CONSTRAINT FK_8C58AD566BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE point_conditions ADD CONSTRAINT FK_28132A03115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE points_users ADD CONSTRAINT FK_FF03EDE3CFFE9AD6 FOREIGN KEY (orders_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE points_users ADD CONSTRAINT FK_FF03EDE3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE product_reviews ADD CONSTRAINT FK_B8A9F0BF4584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE product_reviews ADD CONSTRAINT FK_B8A9F0BFA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE products_categories ADD CONSTRAINT FK_E8ACBE764584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE products_categories ADD CONSTRAINT FK_E8ACBE7612469DE2 FOREIGN KEY (category_id) REFERENCES categories (id)');
        $this->addSql('ALTER TABLE products_cities_prices ADD CONSTRAINT FK_EF0906044584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE products_cities_prices ADD CONSTRAINT FK_EF0906048BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE products_countries_prices ADD CONSTRAINT FK_34E9007A4584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE products_countries_prices ADD CONSTRAINT FK_34E9007AF92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id)');
        $this->addSql('ALTER TABLE products_promotions ADD CONSTRAINT FK_3844C82A139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id)');
        $this->addSql('ALTER TABLE products_promotions ADD CONSTRAINT FK_3844C82A4584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE products_regions_prices ADD CONSTRAINT FK_F6DC7CE34584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE products_regions_prices ADD CONSTRAINT FK_F6DC7CE398260155 FOREIGN KEY (region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE promotions ADD CONSTRAINT FK_EA1B3034115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE promotions ADD CONSTRAINT FK_EA1B30347344E182 FOREIGN KEY (discount_type_id) REFERENCES discount_types (id)');
        $this->addSql('ALTER TABLE regions ADD CONSTRAINT FK_A26779F3F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id)');
        $this->addSql('ALTER TABLE regions_catalogs ADD CONSTRAINT FK_DBCCC50098260155 FOREIGN KEY (region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE regions_catalogs ADD CONSTRAINT FK_DBCCC50053B63F74 FOREIGN KEY (catalogs_id) REFERENCES catalogs (id)');
        $this->addSql('ALTER TABLE regions_categories ADD CONSTRAINT FK_93AF15B398260155 FOREIGN KEY (region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE regions_categories ADD CONSTRAINT FK_93AF15B3A21214B7 FOREIGN KEY (categories_id) REFERENCES categories (id)');
        $this->addSql('ALTER TABLE regions_coupons ADD CONSTRAINT FK_962E852098260155 FOREIGN KEY (region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE regions_coupons ADD CONSTRAINT FK_962E85206D72B15C FOREIGN KEY (coupons_id) REFERENCES coupons (id)');
        $this->addSql('ALTER TABLE regions_domains ADD CONSTRAINT FK_EF312BA598260155 FOREIGN KEY (region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE regions_domains ADD CONSTRAINT FK_EF312BA5115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE regions_modules ADD CONSTRAINT FK_4DFDD7EF98260155 FOREIGN KEY (region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE regions_modules ADD CONSTRAINT FK_4DFDD7EF60D6DC42 FOREIGN KEY (modules_id) REFERENCES modules (id)');
        $this->addSql('ALTER TABLE regions_payment_methods ADD CONSTRAINT FK_7255C7F398260155 FOREIGN KEY (region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE regions_payment_methods ADD CONSTRAINT FK_7255C7F31484032 FOREIGN KEY (payment_methods_id) REFERENCES payment_methods (id)');
        $this->addSql('ALTER TABLE regions_points_conditions ADD CONSTRAINT FK_529709DE98260155 FOREIGN KEY (region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE regions_points_conditions ADD CONSTRAINT FK_529709DE7EF86AD2 FOREIGN KEY (point_condition_id) REFERENCES point_conditions (id)');
        $this->addSql('ALTER TABLE regions_promotions ADD CONSTRAINT FK_434763EF98260155 FOREIGN KEY (region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE regions_promotions ADD CONSTRAINT FK_434763EF139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id)');
        $this->addSql('ALTER TABLE shopping_cart ADD CONSTRAINT FK_72AAD4F6A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE shopping_cart ADD CONSTRAINT FK_72AAD4F64584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE slides ADD CONSTRAINT FK_B8C02091115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE statistics ADD CONSTRAINT FK_E2D38B22115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE template_images ADD CONSTRAINT FK_EBF7B7985DA0FB8 FOREIGN KEY (template_id) REFERENCES templates (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9F92F3E70 FOREIGN KEY (country_id) REFERENCES countries (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E998260155 FOREIGN KEY (region_id) REFERENCES regions (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E98BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id)');
        $this->addSql('ALTER TABLE users_domains ADD CONSTRAINT FK_7C7BCB57A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE users_domains ADD CONSTRAINT FK_7C7BCB57115F0EE5 FOREIGN KEY (domain_id) REFERENCES domains (id)');
    }

    public function down(Schema $schema): void
    {

        $this->addSql('ALTER TABLE catalogs DROP FOREIGN KEY FK_F3AD370A115F0EE5');
        $this->addSql('ALTER TABLE catalogs_products DROP FOREIGN KEY FK_322616D94584665A');
        $this->addSql('ALTER TABLE catalogs_products DROP FOREIGN KEY FK_322616D9CC3C66FC');
        $this->addSql('ALTER TABLE categories DROP FOREIGN KEY FK_3AF34668115F0EE5');
        $this->addSql('ALTER TABLE cities DROP FOREIGN KEY FK_D95DB16B98260155');
        $this->addSql('ALTER TABLE cities_catalogs DROP FOREIGN KEY FK_6E347EBA8BAC62AF');
        $this->addSql('ALTER TABLE cities_catalogs DROP FOREIGN KEY FK_6E347EBA53B63F74');
        $this->addSql('ALTER TABLE cities_categories DROP FOREIGN KEY FK_D1368C7D8BAC62AF');
        $this->addSql('ALTER TABLE cities_categories DROP FOREIGN KEY FK_D1368C7DA21214B7');
        $this->addSql('ALTER TABLE cities_coupons DROP FOREIGN KEY FK_BE5A0E9D8BAC62AF');
        $this->addSql('ALTER TABLE cities_coupons DROP FOREIGN KEY FK_BE5A0E9D6D72B15C');
        $this->addSql('ALTER TABLE cities_domains DROP FOREIGN KEY FK_C745A0188BAC62AF');
        $this->addSql('ALTER TABLE cities_domains DROP FOREIGN KEY FK_C745A018115F0EE5');
        $this->addSql('ALTER TABLE cities_modules DROP FOREIGN KEY FK_65895C528BAC62AF');
        $this->addSql('ALTER TABLE cities_modules DROP FOREIGN KEY FK_65895C5260D6DC42');
        $this->addSql('ALTER TABLE cities_payment_methods DROP FOREIGN KEY FK_D4B5919F8BAC62AF');
        $this->addSql('ALTER TABLE cities_payment_methods DROP FOREIGN KEY FK_D4B5919F1484032');
        $this->addSql('ALTER TABLE cities_points_conditions DROP FOREIGN KEY FK_19D77F548BAC62AF');
        $this->addSql('ALTER TABLE cities_points_conditions DROP FOREIGN KEY FK_19D77F548FD2F6B7');
        $this->addSql('ALTER TABLE cities_promotions DROP FOREIGN KEY FK_1DEFA218BAC62AF');
        $this->addSql('ALTER TABLE cities_promotions DROP FOREIGN KEY FK_1DEFA21139DF194');
        $this->addSql('ALTER TABLE colors_scheme DROP FOREIGN KEY FK_BB9F98FF115F0EE5');
        $this->addSql('ALTER TABLE countries_catalogs DROP FOREIGN KEY FK_4E4A4C10F92F3E70');
        $this->addSql('ALTER TABLE countries_catalogs DROP FOREIGN KEY FK_4E4A4C1053B63F74');
        $this->addSql('ALTER TABLE countries_categories DROP FOREIGN KEY FK_4D09A9E0F92F3E70');
        $this->addSql('ALTER TABLE countries_categories DROP FOREIGN KEY FK_4D09A9E0A21214B7');
        $this->addSql('ALTER TABLE countries_coupons DROP FOREIGN KEY FK_AFED17E8F92F3E70');
        $this->addSql('ALTER TABLE countries_coupons DROP FOREIGN KEY FK_AFED17E86D72B15C');
        $this->addSql('ALTER TABLE countries_domains DROP FOREIGN KEY FK_D6F2B96DF92F3E70');
        $this->addSql('ALTER TABLE countries_domains DROP FOREIGN KEY FK_D6F2B96D115F0EE5');
        $this->addSql('ALTER TABLE countries_modules DROP FOREIGN KEY FK_743E4527F92F3E70');
        $this->addSql('ALTER TABLE countries_modules DROP FOREIGN KEY FK_743E452760D6DC42');
        $this->addSql('ALTER TABLE countries_payment_methods DROP FOREIGN KEY FK_980C4A89F92F3E70');
        $this->addSql('ALTER TABLE countries_payment_methods DROP FOREIGN KEY FK_980C4A891484032');
        $this->addSql('ALTER TABLE countries_points_conditions DROP FOREIGN KEY FK_144E8D66F92F3E70');
        $this->addSql('ALTER TABLE countries_points_conditions DROP FOREIGN KEY FK_144E8D668FD2F6B7');
        $this->addSql('ALTER TABLE countries_promotions DROP FOREIGN KEY FK_9DE1DFBCF92F3E70');
        $this->addSql('ALTER TABLE countries_promotions DROP FOREIGN KEY FK_9DE1DFBC10007789');
        $this->addSql('ALTER TABLE coupons DROP FOREIGN KEY FK_F56411187344E182');
        $this->addSql('ALTER TABLE coupons DROP FOREIGN KEY FK_F5641118115F0EE5');
        $this->addSql('ALTER TABLE discount_types DROP FOREIGN KEY FK_721A51A7115F0EE5');
        $this->addSql('ALTER TABLE domain_module_features DROP FOREIGN KEY FK_DB374446115F0EE5');
        $this->addSql('ALTER TABLE domain_module_features DROP FOREIGN KEY FK_DB374446F50193E4');
        $this->addSql('ALTER TABLE domain_modules DROP FOREIGN KEY FK_CC605ACF115F0EE5');
        $this->addSql('ALTER TABLE domain_modules DROP FOREIGN KEY FK_CC605ACFAFC2B591');
        $this->addSql('ALTER TABLE domain_templates DROP FOREIGN KEY FK_8958AFC0115F0EE5');
        $this->addSql('ALTER TABLE domain_templates DROP FOREIGN KEY FK_8958AFC05DA0FB8');
        $this->addSql('ALTER TABLE domains DROP FOREIGN KEY FK_8C7BBF9D9033212A');
        $this->addSql('ALTER TABLE favorite_products DROP FOREIGN KEY FK_19ED42ABA76ED395');
        $this->addSql('ALTER TABLE favorite_products DROP FOREIGN KEY FK_19ED42AB4584665A');
        $this->addSql('ALTER TABLE help_message_images DROP FOREIGN KEY FK_5E1D162AB9AFDB2B');
        $this->addSql('ALTER TABLE help_messages DROP FOREIGN KEY FK_54399A9629F6EE60');
        $this->addSql('ALTER TABLE help_messages DROP FOREIGN KEY FK_54399A962130303A');
        $this->addSql('ALTER TABLE help_messages DROP FOREIGN KEY FK_54399A9614399779');
        $this->addSql('ALTER TABLE images_products DROP FOREIGN KEY FK_109927304584665A');
        $this->addSql('ALTER TABLE metadata DROP FOREIGN KEY FK_4F143414115F0EE5');
        $this->addSql('ALTER TABLE module_conditions DROP FOREIGN KEY FK_61832234AFC2B591');
        $this->addSql('ALTER TABLE module_conditions DROP FOREIGN KEY FK_61832234F92F3E70');
        $this->addSql('ALTER TABLE module_conditions DROP FOREIGN KEY FK_6183223498260155');
        $this->addSql('ALTER TABLE module_conditions DROP FOREIGN KEY FK_618322348BAC62AF');
        $this->addSql('ALTER TABLE module_features DROP FOREIGN KEY FK_DB000FEDAFC2B591');
        $this->addSql('ALTER TABLE modules_tenants DROP FOREIGN KEY FK_CCB1D58F9033212A');
        $this->addSql('ALTER TABLE modules_tenants DROP FOREIGN KEY FK_CCB1D58FAFC2B591');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEEA76ED395');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE41D46E2E');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEEDED35062');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE6DE4646B');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE6BF700BD');
        $this->addSql('ALTER TABLE orders DROP FOREIGN KEY FK_E52FFDEE66C5951B');
        $this->addSql('ALTER TABLE orders_products DROP FOREIGN KEY FK_749C879CCFFE9AD6');
        $this->addSql('ALTER TABLE orders_products DROP FOREIGN KEY FK_749C879C4584665A');
        $this->addSql('ALTER TABLE payment_methods DROP FOREIGN KEY FK_4FABF983115F0EE5');
        $this->addSql('ALTER TABLE payment_transactions DROP FOREIGN KEY FK_8C58AD56CFFE9AD6');
        $this->addSql('ALTER TABLE payment_transactions DROP FOREIGN KEY FK_8C58AD565AA1164F');
        $this->addSql('ALTER TABLE payment_transactions DROP FOREIGN KEY FK_8C58AD566BF700BD');
        $this->addSql('ALTER TABLE point_conditions DROP FOREIGN KEY FK_28132A03115F0EE5');
        $this->addSql('ALTER TABLE points_users DROP FOREIGN KEY FK_FF03EDE3CFFE9AD6');
        $this->addSql('ALTER TABLE points_users DROP FOREIGN KEY FK_FF03EDE3A76ED395');
        $this->addSql('ALTER TABLE product_reviews DROP FOREIGN KEY FK_B8A9F0BF4584665A');
        $this->addSql('ALTER TABLE product_reviews DROP FOREIGN KEY FK_B8A9F0BFA76ED395');
        $this->addSql('ALTER TABLE products DROP FOREIGN KEY FK_B3BA5A5A115F0EE5');
        $this->addSql('ALTER TABLE products_categories DROP FOREIGN KEY FK_E8ACBE764584665A');
        $this->addSql('ALTER TABLE products_categories DROP FOREIGN KEY FK_E8ACBE7612469DE2');
        $this->addSql('ALTER TABLE products_cities_prices DROP FOREIGN KEY FK_EF0906044584665A');
        $this->addSql('ALTER TABLE products_cities_prices DROP FOREIGN KEY FK_EF0906048BAC62AF');
        $this->addSql('ALTER TABLE products_countries_prices DROP FOREIGN KEY FK_34E9007A4584665A');
        $this->addSql('ALTER TABLE products_countries_prices DROP FOREIGN KEY FK_34E9007AF92F3E70');
        $this->addSql('ALTER TABLE products_promotions DROP FOREIGN KEY FK_3844C82A139DF194');
        $this->addSql('ALTER TABLE products_promotions DROP FOREIGN KEY FK_3844C82A4584665A');
        $this->addSql('ALTER TABLE products_regions_prices DROP FOREIGN KEY FK_F6DC7CE34584665A');
        $this->addSql('ALTER TABLE products_regions_prices DROP FOREIGN KEY FK_F6DC7CE398260155');
        $this->addSql('ALTER TABLE promotions DROP FOREIGN KEY FK_EA1B3034115F0EE5');
        $this->addSql('ALTER TABLE promotions DROP FOREIGN KEY FK_EA1B30347344E182');
        $this->addSql('ALTER TABLE regions DROP FOREIGN KEY FK_A26779F3F92F3E70');
        $this->addSql('ALTER TABLE regions_catalogs DROP FOREIGN KEY FK_DBCCC50098260155');
        $this->addSql('ALTER TABLE regions_catalogs DROP FOREIGN KEY FK_DBCCC50053B63F74');
        $this->addSql('ALTER TABLE regions_categories DROP FOREIGN KEY FK_93AF15B398260155');
        $this->addSql('ALTER TABLE regions_categories DROP FOREIGN KEY FK_93AF15B3A21214B7');
        $this->addSql('ALTER TABLE regions_coupons DROP FOREIGN KEY FK_962E852098260155');
        $this->addSql('ALTER TABLE regions_coupons DROP FOREIGN KEY FK_962E85206D72B15C');
        $this->addSql('ALTER TABLE regions_domains DROP FOREIGN KEY FK_EF312BA598260155');
        $this->addSql('ALTER TABLE regions_domains DROP FOREIGN KEY FK_EF312BA5115F0EE5');
        $this->addSql('ALTER TABLE regions_modules DROP FOREIGN KEY FK_4DFDD7EF98260155');
        $this->addSql('ALTER TABLE regions_modules DROP FOREIGN KEY FK_4DFDD7EF60D6DC42');
        $this->addSql('ALTER TABLE regions_payment_methods DROP FOREIGN KEY FK_7255C7F398260155');
        $this->addSql('ALTER TABLE regions_payment_methods DROP FOREIGN KEY FK_7255C7F31484032');
        $this->addSql('ALTER TABLE regions_points_conditions DROP FOREIGN KEY FK_529709DE98260155');
        $this->addSql('ALTER TABLE regions_points_conditions DROP FOREIGN KEY FK_529709DE7EF86AD2');
        $this->addSql('ALTER TABLE regions_promotions DROP FOREIGN KEY FK_434763EF98260155');
        $this->addSql('ALTER TABLE regions_promotions DROP FOREIGN KEY FK_434763EF139DF194');
        $this->addSql('ALTER TABLE shopping_cart DROP FOREIGN KEY FK_72AAD4F6A76ED395');
        $this->addSql('ALTER TABLE shopping_cart DROP FOREIGN KEY FK_72AAD4F64584665A');
        $this->addSql('ALTER TABLE slides DROP FOREIGN KEY FK_B8C02091115F0EE5');
        $this->addSql('ALTER TABLE statistics DROP FOREIGN KEY FK_E2D38B22115F0EE5');
        $this->addSql('ALTER TABLE template_images DROP FOREIGN KEY FK_EBF7B7985DA0FB8');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9115F0EE5');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9F92F3E70');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E998260155');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E98BAC62AF');
        $this->addSql('ALTER TABLE users_domains DROP FOREIGN KEY FK_7C7BCB57A76ED395');
        $this->addSql('ALTER TABLE users_domains DROP FOREIGN KEY FK_7C7BCB57115F0EE5');
        $this->addSql('DROP TABLE catalogs');
        $this->addSql('DROP TABLE catalogs_products');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE cities');
        $this->addSql('DROP TABLE cities_catalogs');
        $this->addSql('DROP TABLE cities_categories');
        $this->addSql('DROP TABLE cities_coupons');
        $this->addSql('DROP TABLE cities_domains');
        $this->addSql('DROP TABLE cities_modules');
        $this->addSql('DROP TABLE cities_payment_methods');
        $this->addSql('DROP TABLE cities_points_conditions');
        $this->addSql('DROP TABLE cities_promotions');
        $this->addSql('DROP TABLE colors_scheme');
        $this->addSql('DROP TABLE countries');
        $this->addSql('DROP TABLE countries_catalogs');
        $this->addSql('DROP TABLE countries_categories');
        $this->addSql('DROP TABLE countries_coupons');
        $this->addSql('DROP TABLE countries_domains');
        $this->addSql('DROP TABLE countries_modules');
        $this->addSql('DROP TABLE countries_payment_methods');
        $this->addSql('DROP TABLE countries_points_conditions');
        $this->addSql('DROP TABLE countries_promotions');
        $this->addSql('DROP TABLE coupons');
        $this->addSql('DROP TABLE discount_types');
        $this->addSql('DROP TABLE domain_module_features');
        $this->addSql('DROP TABLE domain_modules');
        $this->addSql('DROP TABLE domain_templates');
        $this->addSql('DROP TABLE domains');
        $this->addSql('DROP TABLE favorite_products');
        $this->addSql('DROP TABLE help_message_images');
        $this->addSql('DROP TABLE help_messages');
        $this->addSql('DROP TABLE images_products');
        $this->addSql('DROP TABLE logs');
        $this->addSql('DROP TABLE metadata');
        $this->addSql('DROP TABLE module_conditions');
        $this->addSql('DROP TABLE module_features');
        $this->addSql('DROP TABLE modules');
        $this->addSql('DROP TABLE modules_tenants');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE orders_products');
        $this->addSql('DROP TABLE payment_methods');
        $this->addSql('DROP TABLE payment_transactions');
        $this->addSql('DROP TABLE point_conditions');
        $this->addSql('DROP TABLE points_users');
        $this->addSql('DROP TABLE product_reviews');
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE products_categories');
        $this->addSql('DROP TABLE products_cities_prices');
        $this->addSql('DROP TABLE products_countries_prices');
        $this->addSql('DROP TABLE products_promotions');
        $this->addSql('DROP TABLE products_regions_prices');
        $this->addSql('DROP TABLE promotions');
        $this->addSql('DROP TABLE regions');
        $this->addSql('DROP TABLE regions_catalogs');
        $this->addSql('DROP TABLE regions_categories');
        $this->addSql('DROP TABLE regions_coupons');
        $this->addSql('DROP TABLE regions_domains');
        $this->addSql('DROP TABLE regions_modules');
        $this->addSql('DROP TABLE regions_payment_methods');
        $this->addSql('DROP TABLE regions_points_conditions');
        $this->addSql('DROP TABLE regions_promotions');
        $this->addSql('DROP TABLE shopping_cart');
        $this->addSql('DROP TABLE slides');
        $this->addSql('DROP TABLE statistics');
        $this->addSql('DROP TABLE status');
        $this->addSql('DROP TABLE template_images');
        $this->addSql('DROP TABLE templates');
        $this->addSql('DROP TABLE tenants');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE users_domains');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
